% Output is 116 labels of AAL-Atlas

function [Labels,Label] = lab_get_aal

Labels = {'Precentral_L';'Precentral_R';'Frontal_Sup_L';'Frontal_Sup_R'; ...
    'Frontal_Sup_Orb_L';'Frontal_Sup_Orb_R';'Frontal_Mid_L';'Frontal_Mid_R'; ...
    'Frontal_Mid_Orb_L';'Frontal_Mid_Orb_R';'Frontal_Inf_Oper_L'; ...
    'Frontal_Inf_Oper_R';'Frontal_Inf_Tri_L';'Frontal_Inf_Tri_R'; ...
    'Frontal_Inf_Orb_L';'Frontal_Inf_Orb_R';'Rolandic_Oper_L'; ...
    'Rolandic_Oper_R';'Supp_Motor_Area_L';'Supp_Motor_Area_R'; ...
    'Olfactory_L';'Olfactory_R';'Frontal_Sup_Medial_L';'Frontal_Sup_Medial_R'; ...
    'Frontal_Med_Orb_L';'Frontal_Med_Orb_R';'Rectus_L';'Rectus_R';'Insula_L'; ...
    'Insula_R';'Cingulum_Ant_L';'Cingulum_Ant_R';'Cingulum_Mid_L'; ...
    'Cingulum_Mid_R';'Cingulum_Post_L';'Cingulum_Post_R';'Hippocampus_L'; ...
    'Hippocampus_R';'ParaHippocampal_L';'ParaHippocampal_R';'Amygdala_L'; ...
    'Amygdala_R';'Calcarine_L';'Calcarine_R';'Cuneus_L';'Cuneus_R';'Lingual_L'; ...
    'Lingual_R';'Occipital_Sup_L';'Occipital_Sup_R';'Occipital_Mid_L'; ...
    'Occipital_Mid_R';'Occipital_Inf_L';'Occipital_Inf_R';'Fusiform_L'; ...
    'Fusiform_R';'Postcentral_L';'Postcentral_R';'Parietal_Sup_L'; ...
    'Parietal_Sup_R';'Parietal_Inf_L';'Parietal_Inf_R';'SupraMarginal_L'; ...
    'SupraMarginal_R';'Angular_L';'Angular_R';'Precuneus_L';'Precuneus_R'; ...
    'Paracentral_Lobule_L';'Paracentral_Lobule_R';'Caudate_L';'Caudate_R'; ...
    'Putamen_L';'Putamen_R';'Pallidum_L';'Pallidum_R';'Thalamus_L';'Thalamus_R'; ...
    'Heschl_L';'Heschl_R';'Temporal_Sup_L';'Temporal_Sup_R';'Temporal_Pole_Sup_L'; ...
    'Temporal_Pole_Sup_R';'Temporal_Mid_L';'Temporal_Mid_R';'Temporal_Pole_Mid_L'; ...
    'Temporal_Pole_Mid_R';'Temporal_Inf_L';'Temporal_Inf_R';'Cerebelum_Crus1_L'; ...
    'Cerebelum_Crus1_R';'Cerebelum_Crus2_L';'Cerebelum_Crus2_R';'Cerebelum_3_L'; ...
    'Cerebelum_3_R';'Cerebelum_4_5_L';'Cerebelum_4_5_R';'Cerebelum_6_L'; ...
    'Cerebelum_6_R';'Cerebelum_7b_L';'Cerebelum_7b_R';'Cerebelum_8_L'; ...
    'Cerebelum_8_R';'Cerebelum_9_L';'Cerebelum_9_R';'Cerebelum_10_L'; ...
    'Cerebelum_10_R';'Vermis_1_2';'Vermis_3';'Vermis_4_5';'Vermis_6';'Vermis_7'; ...
    'Vermis_8';'Vermis_9';'Vermis_10'};
Label = {'LPrecent';'RPrecent';'LFroSup';'RFroSup';'LFroSupO';'RFroSupO'; ...
    'LFroMid';'RFroMid';'LFroMidO';'RFroMidO';'LFroInfO';'RFroInfO';'LFroInfT'; ...
    'RFroInfT';'LFroInfO';'RFroInfO';'LRolOpe';'RRolOpe';'LSupMotA';'RSupMotA'; ...
    'LOlfacto';'ROlfacto';'LFroSupM';'RFroSupM';'LFroMedO';'RFroMedO';'LRectus'; ...
    'RRectus';'LInsula';'RInsula';'LCinAnt';'RCinAnt';'LCinMid';'RCinMid';'LCinPos'; ...
    'RCinPos';'LHippoca';'RHippoca';'LParaHip';'RParaHip';'LAmygdal';'RAmygdal'; ...
    'LCalcari';'RCalcari';'LCuneus';'RCuneus';'LLingual';'RLingual';'LOccSup'; ...
    'ROccSup';'LOccMid';'ROccMid';'LOccInf';'ROccInf';'LFusifor';'RFusifor'; ...
    'LPostcen';'RPostcen';'LParSup';'RParSup';'LParInf';'RParInf';'LSupraMa'; ...
    'RSupraMa';'LAngular';'RAngular';'LPrecune';'RPrecune';'LParLob';'RParLob'; ...
    'LCaudate';'RCaudate';'LPutamen';'RPutamen';'LPallidu';'RPallidu';'LThalamu'; ...
    'RThalamu';'LHeschl';'RHeschl';'LTemSup';'RTemSup';'LTemPolS';'RTemPolS'; ...
    'LTemMid';'RTemMid';'LTemPolM';'RTemPolM';'LTemInf';'RTemInf';'LCerCru'; ...
    'RCerCru';'LCerCru';'RCerCru';'LCer3';'RCer3';'LCer45';'RCer45';'LCer6'; ...
    'RCer6';'LCer7b';'RCer7b';'LCer8';'RCer8';'LCer9';'RCer9';'LCer10';'RCer10'; ...
    'Ver12';'Ver3';'Ver45';'Ver6';'Ver7';'Ver8';'Ver9';'Ver10';};