% Create dialog or menu for 'Statistics'
%
% lab_select_statistics(domenu)
%       domenu:  1            create menu in active figure
%                0 or empty   create dialog to select
%
% Written by F. Hatz 2012 Neurology Basel

function lab_select_statistics(domenu)

if ~exist('domenu','var')
    domenu = 0;
end

MenuName = 'Statistics';
SelList = {'Basic Statistics','lab_statistics',''; ...
    'Permutation-Test','lab_permutation',''; ...
    'Repeated Measures Anova','lab_repeatedmeasures',''; ...
    'Random Forest','lab_randomforest','';
    'Support Vector Machine','lab_svm',''; ...
    'Principal Component Analysis','lab_pca',''; ...
    'Generalized Linear Model','lab_glm',''; ...
    'ROC-curve','lab_create_ROC',''; ...
    'Intraclass Correlation','lab_ICC',''; ...
    'Cronbach Alpha','lab_CronbachAlpha',''; ...
    'Coefficient of Variation','lab_CoV',''; ...
    'Correlation','lab_Correlation',''; ...
    'Kappa','lab_kappa',''};

lab_select_menu(MenuName,SelList,domenu);

return