% Create dialog or menu for 'Extra'
%
% lab_select_select(domenu)
%       domenu:  1            create menu in active figure
%                0 or empty   create dialog to select
%
% Written by F. Hatz 2012 Neurology Basel

function lab_select_extra(domenu)

if ~exist('domenu','var')
    domenu = 0;
end

MenuName = 'Extra';
SelList = {'Reduce to Mappings','lab_reduce_matrix2mappings','Matrix'; ...
    'Kmeans clustering','lab_calculate_kmeans','Matrix'; ...
    'Kmeans clustering (Matlab-Container)','lab_matrix_clustering','Matrix'; ...
    'Convert Matrix to Connections','lab_matrix2connections','Matrix'; ...
    'Convert Connections to Matrix','lab_connections2matrix','Matrix'; ...
    'Edit/combine files',{'lab_read_statistics',[],0,0,1,1,1},'Excel'; ...
    'Combine results and outcomes',{'lab_read_statistics',[],1,0,1,1,1},'Excel'; ...
    'Split results by outcome','lab_split_by_outcome','Excel'; ...
    'Combine power results','lab_combine_power','Excel'; ...
    'Reduce to Mappings','lab_xls2mappings','Excel'; ...
    'Combine trials/subjects and variables','lab_measures2trials','Excel'; ...
    'XLS to Matrix','lab_xls2matrix','Excel'; ...
    'Convert BrainWave to Excel',{'lab_import_bw_results',[],[],1},'Brainwave'; ...
    'Combine BrainWave power results','lab_combine_bw_power','Brainwave'; ...
    'Convert BrainWave matrices','lab_convert_bw_matrices','Brainwave'; ...
    'Convert MRI to .hdr','lab_read_mri','MRI'; ...
    'Convert MRI to RAS','lab_correct_mri2RAS','MRI'; ...
    'Coregister MRI/Locations','lab_coreg','MRI'; ...
    'Coregister Atlas to MRI','lab_match_atlas2mri','MRI'; ...
    'Correct Digitizer','lab_correct_digits','MRI'; ...
    'Calculate Leadfield','lab_compute_leadfield','Leadfied'; ...
    'Reduce Leadfield','lab_reduce_LF','Leadfied'; ...
    'Collect','lab_collect_filedata','Files'; ...
    'Create subject folders','lab_create_patientfolders','Files'; ...
    'Change filenames','lab_change_filenames','Files'; ...
    'Find values for quality control','lab_test_quality','Testing'; ...
    'Compare processings','lab_compare_processings','Testing'; ...
    'Smooth data','lab_smoothing','Smoothing'; ...
    'Plot summary results','lab_plot_summed_distances','Smoothing'; ...
    'Create random data','lab_create_modeldata',''; ...
    'Find pairs in 2 groups','lab_find_pairs',''; ...
    'Split DBS/noDBS','lab_detect_dbs',''};


lab_select_menu(MenuName,SelList,domenu);

return