% Plot results in signal or source space (atlas based)
%
% lab_select_plot(domenu)
%       domenu:  1            create menu in active figure
%                0 or empty   create dialog to select
%
% For source space plotting the file 'MNIbrain.mat' is needed
% (see documentation)
%
% Written by F. Hatz 2012

function lab_select_plot(domenu)

if ~exist('domenu','var')
    domenu = 0;
end

MenuName = 'Plot';
SelList = {'EEG','lab_evaluate_eeg',''; ...
    'Results','lab_plot_elec','Signal Space'; ...
    '2D-Electrodes','lab_plot_locs','Signal Space'; ...
    '3D-Electrodes','lab_plot_locs3d','Signal Space'; ...
    'Results','lab_plot_IS','Source Space'; ...
    'Ortho-Slides','lab_plot_mri','Source Space'; ...
    'Dipol Fitting (Mesh)','lab_plot_ISresult','Source Space'; ...
    'Mesh','lab_plot_mesh',''; ...
    'MRI',{'lab_plot_mri',[],1},''; ...
    'Matrix','lab_plot_matrix',''; ...
    'Boxplot/Scatter','lab_xls2plot',''; ...
    'Histogram','lab_plot_histogram',''; ...
    'Distribution','lab_plot_distribution',''; ...
    'Data - matrix','lab_plot_xls2image',''; ...
    'Matrix & Distance','lab_plot_matrix2distance',''; ...
    'Spectrum','lab_plot_spectra','Spectrum'; ...
    'Spectrum & Evaluation','lab_evaluate_spectras','Spectrum'; ...
    'Topo-Plots','lab_plot_topos',''; ...
    'Topo-Video','lab_topos2video',''};

lab_select_menu(MenuName,SelList,domenu);

return